/* Goal reflections and optional private photo benchmarks. No photos enter public code or localStorage. */
(() => {
 'use strict';const M=window.strydeProgressModel,ROOT=document.getElementById('root');if(!M)return;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let active=null,dialog=null,urls=[],version=0;
 const media=()=>window.strydePrivatePhotos;
 const signed=()=>window.strydeAccountStatus?.().signedIn;
 const feelings=['Not recorded','Drained','Tough','Okay','Strong','Great'];
 function revoke(){urls.forEach(URL.revokeObjectURL);urls=[];}
 function close(){dialog?.close()}
 function modal(title,body){close();version++;revoke();const d=document.createElement('dialog');d.className='hub-dialog';d.innerHTML='<div class="hub-dialog-top"><h2>'+esc(title)+'</h2><button type="button" data-journal="close" aria-label="Close">×</button></div>'+body;document.body.append(d);dialog=d;d.addEventListener('close',()=>{d.remove();if(dialog===d){version++;revoke();dialog=null;}});d.showModal();return d;}
 function reflect(id){const goal=state.milestones?.find(m=>m.id===id);if(!goal)return;active={type:'goal',id};
  modal(goal.title,`<form class="hub-form" id="goal-reflection-form" data-goal="${esc(id)}"><div class="eyebrow">YOUR REFLECTION</div><p>Capture what happened and what you learned—not just whether you hit a number.</p><div class="hub-fields"><label>Date<input type="date" name="date" value="${M.iso()}" max="${M.iso()}" required></label><label>How did it feel?<select name="feeling">${feelings.map((x,i)=>`<option value="${i}">${x}</option>`).join('')}</select></label></div><label>What happened? How did you feel?<textarea name="reflection" maxlength="2500" required placeholder="What went well, what was difficult…"></textarea></label><label>What will you do next?<textarea name="next" maxlength="1000" placeholder="One thing to repeat or change"></textarea></label><button class="btn orange">Save reflection</button></form><section class="hub-card"><h3>Reflection history</h3><div id="goal-reflection-list"></div></section><section class="hub-card"><h3>Photos for this milestone</h3>${uploadForm('progress')}<div class="journal-photo-list"></div></section>`);
  reflections(id);void loadPhotos();
 }
 function reflections(id){const node=dialog?.querySelector('#goal-reflection-list');if(!node)return;const entries=state.goalReflections?.[id]||[];node.innerHTML=entries.slice().reverse().map(r=>`<article class="hub-reflection"><small>${esc(r.date)} · ${feelings[Number(r.feeling)]||'Not rated'}</small><p>${esc(r.reflection)}</p>${r.next?'<p><b>Next:</b> '+esc(r.next)+'</p>':''}<button class="hub-link" data-journal="delete-reflection" data-goal="${esc(id)}" data-id="${r.id}">Remove</button></article>`).join('')||'<p>No reflections saved yet.</p>';}
 function uploadForm(stage){return `<form class="hub-form journal-upload"><p class="hub-footnote">Optional. Photos go only to your signed-in account’s private storage. They are never published on GitHub or analyzed for body fat.</p><label>Photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" required></label><div class="hub-fields"><label>Photo date<input name="date" type="date" value="${M.iso()}" max="${M.iso()}" required></label><label>View<select name="view"><option value="front">Front</option><option value="side">Side</option><option value="back">Back</option><option value="other">Other</option></select></label></div><label>Checkpoint<select name="stage"><option value="baseline" ${stage==='baseline'?'selected':''}>Baseline</option><option value="followup" ${stage==='followup'?'selected':''}>Follow-up comparison</option><option value="progress" ${stage==='progress'?'selected':''}>Progress photo</option></select></label><label>Caption (optional)<input name="caption" maxlength="500"></label><p class="journal-photo-status" role="status"></p><button class="btn orange" type="submit">Upload private photo</button></form>`;}
 async function compress(file){
  if(!file||file.size>20971520)throw Error('Choose a photo under 20 MB.');
  if(!/^image\/(jpeg|png|webp|heic|heif)$/.test(file.type))throw Error('Use a JPEG, PNG, WebP, or a supported iPhone photo.');
  const src=URL.createObjectURL(file),im=new Image();
  try{await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(Error('This photo format could not be read. Export it as JPEG and try again.'));im.src=src});
   const scale=Math.min(1,1600/Math.max(im.naturalWidth,im.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(im.naturalWidth*scale));canvas.height=Math.max(1,Math.round(im.naturalHeight*scale));const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height);
   const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.86));if(!blob||blob.size>4194304)throw Error('Photo is too large after resizing. Choose a smaller image.');return blob;
  }finally{URL.revokeObjectURL(src)}
 }
 async function loadPhotos(){const box=dialog?.querySelector('.journal-photo-list');if(!box||!active)return;const context={...active},thisVersion=++version;revoke();
  if(!signed()){box.innerHTML='<p>Log in to upload and view your private photos.</p><button class="btn" data-journal="login">Log in</button>';return;}
  box.textContent='Loading private photos…';try{const list=await media().list(context.type,context.id);if(thisVersion!==version||!dialog)return;
   box.innerHTML=list.length?'<div class="journal-compare"><label>Compare the same view<select data-photo-view><option value="all">All views</option><option value="front">Front</option><option value="side">Side</option><option value="back">Back</option><option value="other">Other</option></select></label><div class="journal-gallery"></div></div>':'<p>No photos uploaded yet.</p>';
   const gallery=box.querySelector('.journal-gallery');
   for(const p of list){if(thisVersion!==version)return;const figure=document.createElement('figure');figure.dataset.photoView=p.view_label;figure.innerHTML=`<div class="journal-image-placeholder">Loading photo…</div><figcaption><b>${esc(p.stage)} · ${esc(p.view_label)}</b><span>${esc(p.photo_date)}</span><p>${esc(p.caption)}</p><button class="hub-link" data-journal="delete-photo" data-id="${esc(p.id)}">Delete photo</button></figcaption>`;gallery.append(figure);
    try{const blob=await media().download(p.object_path);if(thisVersion!==version)return;const url=URL.createObjectURL(blob);urls.push(url);const img=document.createElement('img');img.src=url;img.alt=p.stage+' '+p.view_label+' progress photo from '+p.photo_date;img.loading='lazy';figure.querySelector('.journal-image-placeholder').replaceWith(img);}catch{figure.querySelector('.journal-image-placeholder').textContent='Photo unavailable. Reopen to retry.';}
   }
  }catch(e){if(thisVersion===version)box.textContent=e.message||'Unable to load photos.';}
 }
 function benchmarkMarkup(){const list=state.benchmarkCycles||[];return `<section class="hub-card"><div class="eyebrow">OPTIONAL PHOTO BENCHMARKS</div><h2>Your first day. Your next chapter.</h2><p>Start a photo comparison over 100 days, or choose another interval. Use similar lighting, clothing, pose and camera distance. No automated body-shape or body-fat judgments.</p><button class="btn orange" data-journal="new-benchmark">Start a photo benchmark</button></section>${list.map(b=>`<article class="hub-card"><h3>${esc(b.title)}</h3><p>Day 1: ${esc(b.startDate)} · Day ${b.days}: ${esc(b.targetDate)}</p><span class="hub-badge">${b.followupLoggedOn?'Follow-up recorded':M.iso()>=b.targetDate?'Comparison date reached · photo optional':Math.max(0,M.days(M.iso(),b.targetDate))+' days until comparison'}</span><button class="btn" data-journal="benchmark" data-id="${b.id}">Photos & reflection →</button></article>`).join('')}`;}
 function newBenchmark(){modal('Set your photo benchmark',`<form id="new-benchmark-form" class="hub-form"><label>Name<input name="title" maxlength="100" value="My 100-day progress" required></label><div class="hub-fields"><label>Day 1<input type="date" name="start" value="${M.iso()}" max="${M.iso()}" required></label><label>Compare on day<input type="number" name="days" step="1" min="2" max="730" value="100" required></label></div><p>The first date is Day 1; Day 100 is 99 days later. Photos are optional and private.</p><button class="btn orange">Save benchmark</button></form>`);}
 function openBenchmark(id){const b=(state.benchmarkCycles||[]).find(b=>b.id===id);if(!b)return;active={type:'benchmark',id};modal(b.title,`<p>Day 1: ${esc(b.startDate)} · Day ${b.days}: ${esc(b.targetDate)}</p><p>Choose front, side or back consistently when comparing. Use the view filter to place matching photos side by side.</p>${uploadForm(M.iso()>=b.targetDate?'followup':'baseline')}<div class="journal-photo-list"></div><form id="benchmark-reflection-form" class="hub-form" data-id="${id}"><label>What changed beyond the photo?<textarea name="note" maxlength="2000" placeholder="Energy, confidence, running and strength…">${esc(b.reflection||'')}</textarea></label><button class="btn">Save reflection</button></form>`);void loadPhotos();}
 function goals(){ROOT.innerHTML=header()+`<div class="hub-heading"><div class="eyebrow">GOALS & REFLECTIONS</div><h1>Your next chapters.</h1><p>A milestone is more than a finish line. Keep the story, photos and lessons with it.</p></div>${(state.milestones||[]).map(m=>`<article class="hub-card"><span class="hub-badge ${m.status==='completed'?'complete':''}">${esc(m.status)}</span><h2>${esc(m.title)}</h2><p>${esc(m.date)}</p><div class="hub-actions"><button class="btn orange" data-journal="reflect" data-id="${esc(m.id)}">Reflect & photos</button>${m.status==='planned'||m.status==='paused'?`<button class="btn" data-journal="activate-goal" data-id="${esc(m.id)}">Set active</button>`:''}${m.status!=='completed'?`<button class="btn" data-journal="finish-goal" data-id="${esc(m.id)}">Mark complete</button>`:''}</div></article>`).join('')}<section class="hub-card"><h3>Add your next milestone</h3><form class="hub-form" id="hub-goal-form"><label>Goal<input name="title" maxlength="100" required placeholder="e.g. My next 10K"></label><label>Target date<input name="date" type="date" min="${M.iso()}" required></label><label>Focus<select name="kind"><option value="race">Running event</option><option value="strength">Strength</option><option value="general">General fitness</option><option value="recomposition">Body recomposition</option></select></label><button class="btn orange">Add milestone</button></form><p class="hub-footnote">New milestones are queued without erasing history. This update adds tracking and reflection; it does not generate a new race-training plan automatically.</p></section>`;document.getElementById('nav').innerHTML=navHTML();}
 const prev=window.render;window.render=function(...args){if(view==='goals'){goals();return;}return prev.apply(this,args)};
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-journal]');if(!b)return;const a=b.dataset.journal;
  if(a==='close')close();else if(a==='reflect')reflect(b.dataset.id);else if(a==='new-benchmark')newBenchmark();else if(a==='benchmark')openBenchmark(b.dataset.id);else if(a==='login'){close();window.strydeOpenAccount?.();}
  else if(a==='activate-goal'){if(confirm('Make this your active milestone? The current training plan is preserved; a new plan is not generated automatically.')){state.milestones.forEach(m=>{if(m.status==='active')m.status='paused';if(m.id===b.dataset.id)m.status='active';});save();goals();}}
  else if(a==='finish-goal'&&confirm('Mark this milestone completed? Your history stays intact.')){const m=state.milestones.find(m=>m.id===b.dataset.id);m.status='completed';m.completedOn=M.iso();save();goals();}
  else if(a==='delete-reflection'&&confirm('Remove this reflection?')){state.goalReflections[b.dataset.goal]=state.goalReflections[b.dataset.goal].filter(r=>r.id!==b.dataset.id);save();reflections(b.dataset.goal);}
  else if(a==='delete-photo'&&confirm('Permanently delete this private photo?')){b.disabled=true;try{await media().remove(b.dataset.id);await loadPhotos();}catch(err){alert(err.message);b.disabled=false;}}
 });
 document.addEventListener('change',e=>{if(e.target.hasAttribute('data-photo-view')){const v=e.target.value;dialog.querySelectorAll('[data-photo-view].journal-gallery figure, .journal-gallery figure').forEach(f=>f.hidden=v!=='all'&&f.dataset.photoView!==v)}});
 document.addEventListener('submit',async e=>{
  const form=e.target;
  if(form.id==='goal-reflection-form'){e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),id=form.dataset.goal,date=String(f.get('date'));if(!M.validDate(date)||date>M.iso())return;if(!state.goalReflections)state.goalReflections={};if(!Array.isArray(state.goalReflections[id]))state.goalReflections[id]=[];state.goalReflections[id].push({id:crypto.randomUUID(),date,feeling:Number(f.get('feeling')),reflection:String(f.get('reflection')).trim(),next:String(f.get('next')||'').trim()});save();form.reset();form.elements.date.value=M.iso();reflections(id);}
  else if(form.id==='hub-goal-form'){e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form);state.milestones.push({id:crypto.randomUUID(),title:String(f.get('title')).trim(),date:String(f.get('date')),kind:String(f.get('kind')),status:state.milestones.some(m=>m.status==='active')?'planned':'active'});save();goals();}
  else if(form.id==='new-benchmark-form'){e.preventDefault();if(!form.reportValidity())return;const f=new FormData(form),start=String(f.get('start')),days=Number(f.get('days'));if(!M.validDate(start)||start>M.iso()||!Number.isInteger(days)||days<2||days>730)return;const b={id:crypto.randomUUID(),title:String(f.get('title')),startDate:start,days,targetDate:M.add(start,days-1),reflection:''};if(!Array.isArray(state.benchmarkCycles))state.benchmarkCycles=[];state.benchmarkCycles.push(b);save();close();window.strydeTrainingHub.setTab('photos');openBenchmark(b.id);}
  else if(form.id==='benchmark-reflection-form'){e.preventDefault();const b=state.benchmarkCycles.find(b=>b.id===form.dataset.id);if(b){b.reflection=form.elements.note.value;save();form.querySelector('button').textContent='Reflection saved';}}
  else if(form.classList.contains('journal-upload')){e.preventDefault();if(!form.reportValidity()||!active)return;const status=form.querySelector('.journal-photo-status'),button=form.querySelector('button[type=submit]'),context={...active};button.disabled=true;status.textContent='Preparing your private photo…';
   try{const uploadUid=window.strydeAccountStatus?.().userId;if(!signed())throw Error('Log in first. Photos are never uploaded anonymously.');const f=new FormData(form),date=String(f.get('date'));if(!M.validDate(date)||date>M.iso())throw Error('Choose an actual photo date.');const blob=await compress(f.get('photo'));if(uploadUid!==window.strydeAccountStatus?.().userId)throw Error('Account changed. Reopen the photo form.');await media().upload(blob,{reference_type:context.type,reference_id:context.id,stage:String(f.get('stage')),view_label:String(f.get('view')),photo_date:date,caption:String(f.get('caption')||'')});if(context.type==='benchmark'){const b=(state.benchmarkCycles||[]).find(x=>x.id===context.id);if(b){if(f.get('stage')==='followup')b.followupLoggedOn=date;if(f.get('stage')==='baseline')b.baselineLoggedOn=date;save();}}status.textContent='Private photo saved. Camera metadata is removed during resizing.';form.elements.photo.value='';await loadPhotos();}catch(err){status.textContent=err.message||'Unable to save photo.';}finally{button.disabled=false;}}
 });
 window.addEventListener('stryde-account-change',()=>{version++;revoke();if(dialog?.querySelector('.journal-photo-list')){close();}});
 window.strydeMilestonePhotos={benchmarkMarkup,mount:()=>{},compress};
})();
