/* STRYDE training review, actual-date extra workouts, body checks and visual calendar. */
(() => {
 'use strict';
 const M=window.strydeProgressModel,ROOT=document.getElementById('root');if(!M||!ROOT)return;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rnd=(v,d=1)=>v==null?'—':Number(v).toFixed(d).replace(/\.0$/,'');
 const percent=v=>v==null?'Building baseline':(v>0?'+':'')+rnd(v)+'%';
 const pace=v=>{if(v==null)return '—';const seconds=Math.round(v*60);return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')+'/km'};
 const dateLabel=s=>M.validDate(s)?new Date(s+'T12:00:00Z').toLocaleDateString([],{month:'short',day:'numeric',timeZone:'UTC'}):s;
 let month=M.iso().slice(0,7),tab='overview',calendarMode='week',calendarMonth=month,dialog=null,extraRows=[],extraDraft=null;
 const snapshot=()=>window.strydeStravaSnapshot?.()||{rows:[],loaded:false,connected:false};
 const all=()=>M.records(state,snapshot().rows);
 const safeSave=()=>{try{save();return true}catch{alert('Unable to save on this device. Export a backup before closing STRYDE.');return false}};
 function modal(title,body){
  dialog?.close();dialog?.remove();dialog=document.createElement('dialog');dialog.className='hub-dialog';dialog.innerHTML='<div class="hub-dialog-top"><h2>'+esc(title)+'</h2><button type="button" data-hub="close" aria-label="Close">×</button></div>'+body;document.body.append(dialog);
  const closing=dialog;closing.addEventListener('close',()=>{closing.remove();if(dialog===closing)dialog=null});dialog.showModal();return dialog;
 }
 function close(){dialog?.close()}
 function counts(a){return `<div class="hub-stats"><div><span>Runs</span><strong>${a.runCount}</strong><small>${rnd(a.km)} km recorded</small></div><div><span>Strength workouts</span><strong>${a.liftCount}</strong><small>Completed, not scheduled</small></div><div><span>Training days</span><strong>${new Set(a.rows.map(r=>r.date)).size}</strong><small>Extra activities included</small></div><div><span>Full training time</span><strong>${rnd(a.minutes/60)}<em> h</em></strong><small>Only durations you logged</small></div></div>`;}
 function nextLift(r){const t=target(r.i),e=EX[r.i];return `Next ${e.name}: ${t.weight||'calibrate'} ${e.unit}, ${e.sets} × ${t.reps}. ${t.why}`;}
 function coach(a){
  const insights=[];
  if(a.loadWinner){const r=a.loadWinner;insights.push({label:'YOUR BIGGEST LOAD GAIN',title:r.name,what:`${rnd(r.first.weight)} → ${rnd(r.last.weight)} ${r.last.unit} (${percent(r.load)}), with at least the same reps per set.`,meaning:'This is a comparable load increase in your log, not a measured percentage of muscle growth.',next:nextLift(r)});}
  else if(a.changes.length){const r=a.changes[0];insights.push({label:'YOUR STRONGEST SIGNAL',title:r.name,what:`${percent(r.output)} in load × average reps per set, across ${r.sessions} comparable logs.`,meaning:r.rep>0&&Math.abs(r.load)<.01?'You completed more reps at the same weight. That is real rep progress even without heavier weights.':'This describes recorded set output, not a clinical strength test.',next:nextLift(r)});}
  else insights.push({label:'START WITH COMPARABLE LOGS',title:'Build your strength baseline',what:`${a.liftCount} strength workout${a.liftCount===1?'':'s'} recorded in this period.`,meaning:'An improvement percentage needs repeat logs of the same lift, unit, set count and effort, with good form confirmed.',next:'Log every working set, how hard it felt, and whether the technique stayed controlled. One session is not a trend.'});
  if(a.runTrend){const r=a.runTrend;insights.push({label:'RUNNING · EARLY SIGNAL',title:percent(r.change)+' observed pace change',what:`${pace(r.oldPace)} → ${pace(r.newPace)} on ${rnd(r.first.distance)} and ${rnd(r.last.distance)} km runs (${r.basis} time).`,meaning:'Distances are within 10%. Route, effort and weather are not fully matched, so this is not a fitness-gain score.',next:'Keep easy days conversational. Compare another similar route at a similar effort before chasing a faster pace.'});}
  else insights.push({label:'RUNNING',title:a.runCount?'Consistency before a pace score':'Your first run starts the trend',what:a.runCount?`${a.runCount} run${a.runCount===1?'':'s'} and ${rnd(a.km)} km recorded.`:'No completed run is available for this period.',meaning:'A pace comparison needs at least two similar-distance runs using the same timing basis. A longer run is not automatically a faster-run improvement.',next:snapshot().loaded?'Keep the planned easy effort and save the real distance and times after each run.':'Sync Strava to include your recorded runs in this review.'});
  const rough=a.rows.filter(r=>r.kind==='strength'&&Object.values(r.exercises||{}).some(e=>e.form==='unsure'||e.effort==='hard'));
  if(rough.length)insights.push({label:'WHAT TO WATCH',title:'Technique comes before a load increase',what:`${rough.length} session${rough.length===1?'':'s'} include hard effort or unconfirmed form.`,meaning:'These sessions are excluded from the comparable-lift percentage. An unchanged score is not a failure.',next:'Use the same or a lighter load until the movement is controlled. Stop for pain rather than using the score to push through.'});
  return `<section class="hub-coach"><div class="eyebrow">YOUR COACHING REVIEW</div><h2>What your training means.</h2>${insights.map(i=>`<article><small>${i.label}</small><h3>${esc(i.title)}</h3><p><b>What changed:</b> ${esc(i.what)}</p><p><b>What it means:</b> ${esc(i.meaning)}</p><p class="hub-next"><b>Next:</b> ${esc(i.next)}</p></article>`).join('')}<p class="hub-footnote">Transparent rules, not a human assessment or injury diagnosis. Missing logs, changed equipment and unreported fatigue limit the analysis.</p></section>`;
 }
 function methodology(){return `<details class="hub-method"><summary>How improvement is calculated</summary><p><b>Lifting:</b> for each repeated exercise, compare the first and latest matching sessions in the selected month. Unit, set count, recorded setup and effort must match; both need controlled form. Set output = load × average reps per set. The overall percentage is the median of at least two matched lift changes. Extra sets alone do not increase it.</p><p><b>Biggest load gain:</b> the largest percentage increase in working weight among those matched lifts, with reps per set maintained. Unknown machine setup is flagged. This is not a percentage of muscle gained.</p><p><b>Running:</b> compare earlier and later runs within 10% distance, using the same time basis. Known terrain, effort and elevation must be comparable. Pace change = (old pace − new pace) / old pace. Weather and effort are not fully controlled; it is an observed pace change, not a fitness score.</p><p>Only completed records count. Calendar × means no completion was logged, not proof you skipped training. Possible duplicates are flagged for review. Body-weight change never increases your training score.</p></details>`;}
 function strength(a){return `<section class="hub-card"><div class="eyebrow">LIFTING PROGRESS</div><h2>${a.performance==null?'Building your baseline':percent(a.performance)}</h2><p>${a.performance==null?'Need at least two matching lifts to summarize this month. Individual comparisons appear as soon as they qualify.':'Median change in load × reps per set, first → latest matching sessions this month.'}</p>${a.changes.map(r=>`<article class="hub-lift"><header><h3>${esc(r.name)}</h3><strong>${percent(r.output)}</strong></header><p>${dateLabel(r.first.date)} → ${dateLabel(r.last.date)} · ${r.sessions} matching sessions</p><div class="hub-pair"><span><small>Load</small>${rnd(r.first.weight)} → ${rnd(r.last.weight)} ${esc(r.last.unit)}</span><span><small>Average reps / set</small>${rnd(r.first.reps)} → ${rnd(r.last.reps)}</span></div>${r.setupUnknown?'<small class="hub-warning">Machine/setup not recorded. Only compare these numbers if you used the same setup.</small>':''}</article>`).join('')||'<p class="hub-empty">Repeat a lift and log reps, effort and form. Your RDL starting reference stays in its exercise screen—not as a permanent Progress tile.</p>'}</section>${methodology()}`;}
 function body(){const b=M.due(),last=b.last,prior=b.checks.length>1?b.checks[b.checks.length-2]:null;const points=b.checks.slice(-16);let svg='';
  if(points.length>1){const lo=Math.min(...points.map(x=>x.kg))-.5,hi=Math.max(...points.map(x=>x.kg))+.5,x=d=>20+280*M.days(points[0].date,d)/Math.max(1,M.days(points[0].date,points.at(-1).date)),y=v=>110-80*(v-lo)/(hi-lo);svg=`<svg class="hub-weight-chart" viewBox="0 0 320 145" role="img" aria-label="Recorded body-weight trend; not a fat-loss estimate"><path d="${points.map((p,i)=>(i?'L':'M')+x(p.date).toFixed(1)+','+y(p.kg).toFixed(1)).join(' ')}" fill="none" stroke="#fc4c02" stroke-width="2.5"/>${points.map(p=>`<circle cx="${x(p.date)}" cy="${y(p.kg)}" r="3.5" fill="#fc4c02"><title>${p.date}: ${p.kg} kg</title></circle>`).join('')}<text x="20" y="137">${dateLabel(points[0].date)}</text><text x="248" y="137">${dateLabel(points.at(-1).date)}</text></svg>`;}
  return `<section class="hub-card"><div class="eyebrow">BODY WEIGHT · SEPARATE FROM LIFTING</div><h2>${last?rnd(last.kg)+' kg':'Your first check-in'}</h2><p>${last?'Recorded '+dateLabel(last.date)+(prior?' · '+(last.kg-prior.kg>0?'+':'')+rnd(last.kg-prior.kg)+' kg since the previous check':''):'Enter a dated measurement. Your profile weight is not automatically counted as a new check-in.'}</p>${svg}<form id="hub-weight-form" class="hub-form"><div class="hub-fields"><label>Body weight (kg)<input name="kg" type="number" min="20" max="400" step="0.1" required inputmode="decimal" placeholder="e.g. 57.8"></label><label>Date<input name="date" type="date" max="${M.iso()}" value="${M.iso()}" required></label></div><label>Optional note<input name="note" maxlength="250" placeholder="Time of day, how you felt…"></label><button class="btn orange">Save weight check</button></form><p class="hub-footnote">Compare under similar conditions when practical. Scale weight is not a body-fat measurement. STRYDE does not reward a lower number.</p></section><section class="hub-card"><h3>Weight-check reminders</h3><p>${b.enabled?(b.isDue?'Your next check-in is due.':'Next check: '+dateLabel(b.next)):'Reminders are off.'}</p><form id="hub-weight-settings" class="hub-form"><label>Check-in frequency<select name="cadence">${[7,14,28].map(n=>`<option value="${n}" ${b.interval===n?'selected':''}>Every ${n} days</option>`).join('')}</select></label><label class="hub-check"><input name="enabled" type="checkbox" ${b.enabled?'checked':''}>Show gentle due reminders in STRYDE</label><button class="btn">Save reminder settings</button><button type="button" class="hub-link" data-hub="snooze-weight">Remind me tomorrow</button></form><p class="hub-footnote">In-app reminders appear when you open STRYDE. Phone notifications are a separate reminder service, not background notifications from this page.</p></section><section class="hub-card"><h3>Check-in history</h3>${b.checks.slice().reverse().map(x=>`<div class="hub-record"><div><b>${rnd(x.kg)} kg</b><small>${dateLabel(x.date)} ${esc(x.note||'')}</small></div><button class="hub-link" data-hub="delete-weight" data-id="${esc(x.id)}">Remove</button></div>`).join('')||'<p>No dated checks yet.</p>'}</section>`;
 }
 function progress(){const p=M.period(month),a=M.analyze(all(),p),s=snapshot();ROOT.innerHTML=header()+`<section class="hub-heading"><div class="eyebrow">PROGRESS · MADE MEANINGFUL</div><h1>Your training, explained.</h1><label class="hub-month-label">Review month<input type="month" id="hub-month" value="${month}" max="${M.iso().slice(0,7)}"></label></section><div class="hub-tabs" role="tablist">${['overview','strength','body','photos'].map(t=>`<button role="tab" aria-selected="${tab===t}" class="${tab===t?'active':''}" data-hub="tab" data-tab="${t}">${{overview:'Overview',strength:'Lifting',body:'Body weight',photos:'Photos'}[t]}</button>`).join('')}</div><div class="hub-content">${tab==='overview'?counts(a)+`<div class="hub-stats hub-score-stats"><div><span>Observed run pace</span><strong>${a.runTrend?percent(a.runTrend.change):'—'}</strong><small>${a.runTrend?'Comparable-distance pair, not a fitness score':'Need similar-distance runs'}</small></div><div><span>Lifting set output</span><strong>${a.performance!==null?percent(a.performance):'—'}</strong><small>${a.performance!==null?'Load × reps/set, not muscle growth':'Building comparable lift history'}</small></div></div><p class="hub-footnote">${dateLabel(p.start)}–${dateLabel(p.end)}. ${s.loaded?'Includes loaded Strava runs.':'Strava history has not finished loading; counts may change after sync.'} ${s.limited?'Strava history is capped; older activity totals may be incomplete.':''}</p>`+coach(a)+(a.duplicates.length?`<section class="hub-card"><h3>Possible duplicate runs</h3><p>These manual entries look similar to imported runs. They are still counted separately until you confirm.</p>${a.duplicates.map(d=>`<div class="hub-record"><span>${dateLabel(d.manual.date)} · ${rnd(d.manual.distance)} km</span><button class="btn" data-hub="merge-run" data-id="${esc(d.manual.id)}" data-strava="${d.imported.stravaId}">Same run</button></div>`).join('')}</section>`:'')+`<section class="hub-card"><h3>Completed this month</h3>${a.rows.map(r=>`<div class="hub-record"><div><b>${esc(r.name)}</b><small>${dateLabel(r.date)} · ${esc(r.source)}</small></div><span>${r.kind==='run'?rnd(r.distance)+' km':r.minutes?rnd(r.minutes)+' min':'Sets logged'}</span>${r.source==='Extra workout'?`<button class="hub-link" data-hub="delete-extra" data-id="${esc(r.id.slice(6))}">Remove</button>`:''}</div>`).join('')||'<p>No completed workouts recorded yet.</p>'}<button class="btn" data-hub="extra">Log extra workout</button></section>`+methodology()+'<div data-run-anchor></div>':tab==='strength'?strength(a):tab==='body'?body():window.strydeMilestonePhotos?.benchmarkMarkup?.()||'<section class="hub-card"><h3>Private photo benchmarks</h3><p>Loading photo tools…</p></section>'}</div>`;document.getElementById('nav').innerHTML=navHTML();
  if(tab==='overview'){window.strydeMountRuns?.();window.strydeWorkoutTimer?.mount();const host=ROOT.querySelector('.hub-content');for(const panel of ROOT.querySelectorAll('#stryde-runs-panel,.workout-timing-history'))host?.append(panel);}if(tab==='photos')window.strydeMilestonePhotos?.mount?.();
 }
 function extra(date=M.iso()){
  const actual=M.validDate(date)&&date<=M.iso()?date:M.iso();extraRows=[];extraDraft={date:actual};
  modal('Log extra workout',`<form id="hub-extra-form" class="hub-form"><p>Save what you actually did. This will not replace a recovery day or complete another planned session.</p><div class="hub-fields"><label>Activity<select name="kind" id="hub-extra-kind"><option value="strength">Strength workout</option><option value="run">Run</option><option value="walk">Walk</option><option value="other">Other activity</option></select></label><label>Actual date<input name="date" type="date" value="${actual}" max="${M.iso()}" required></label></div><label>Workout name<input name="name" maxlength="100" placeholder="e.g. Glutes & legs"></label><label>Full workout duration (minutes)<input name="minutes" type="number" min="1" max="1440" step="1" required inputmode="numeric"></label><section data-extra-run hidden><div class="hub-fields"><label>Distance (km)<input name="km" type="number" min="0.1" max="200" step="0.01"></label><label>Effort (1–10)<input name="rpe" type="number" min="1" max="10"></label></div><label>Terrain<select name="terrain"><option value="">Not recorded</option><option value="flat">Flat outdoors</option><option value="hills">Hills</option><option value="treadmill">Treadmill</option><option value="trail">Trail</option></select></label><p class="hub-footnote">Do not manually enter a run that will also import from Strava; link duplicates in Progress when needed.</p></section><section data-extra-strength><h3>Your exercises</h3><div id="hub-extra-exercises"></div><div class="hub-fields"><select id="hub-add-exercise" aria-label="Choose an exercise">${EX.map((e,i)=>`<option value="${i}">${esc(e.name)}</option>`).join('')}</select><button type="button" class="btn" data-hub="add-exercise">Add exercise</button></div><p class="hub-footnote">Add the lifts you did. Leave unrelated exercises out. Reps can be entered as 10,10,8.</p></section><label>Notes<textarea name="notes" maxlength="1000" placeholder="How did the session feel?"></textarea></label><p class="hub-error" role="alert"></p><button class="btn orange" type="submit">Save actual workout</button></form>`);
 }
 function addExercise(){const i=Number(dialog.querySelector('#hub-add-exercise').value);if(extraRows.includes(i))return;extraRows.push(i);const e=EX[i],box=document.createElement('fieldset');box.dataset.extraExercise=i;box.innerHTML=`<legend>${esc(e.name)}</legend><div class="hub-fields"><label>Weight (${esc(e.unit)})<input name="weight${i}" type="number" min="0.1" max="2000" step="any" required></label><label>Reps by set<input name="reps${i}" required placeholder="10,10,10" pattern="[0-9, ]+"></label></div><label>Effort<select name="effort${i}"><option value="unknown">Not recorded</option><option value="easy">Easy · 4+ reps left</option><option value="moderate">Controlled · 2–3 left</option><option value="hard">Hard · 0–1 left</option></select></label><label>Form<select name="form${i}"><option value="unsure">Not confirmed</option><option value="good">Controlled and pain-free</option></select></label><label>Machine / setup (optional)<input name="setup${i}" maxlength="80" placeholder="e.g. same cable machine"></label><button type="button" class="hub-link" data-hub="remove-exercise" data-i="${i}">Remove exercise</button>`;dialog.querySelector('#hub-extra-exercises').append(box);}
 function saveExtra(form){const data=new FormData(form),kind=String(data.get('kind')),date=String(data.get('date')),minutes=M.n(data.get('minutes'));if(!M.validDate(date)||date>M.iso()||!(minutes>=1&&minutes<=1440))throw Error('Enter an actual date and duration.');const ex={};
  if(kind==='strength')for(const i of extraRows){const weight=M.n(data.get('weight'+i)),r=String(data.get('reps'+i)||'').split(',').map(x=>Number(x.trim()));if(!(weight>0)||!r.length||r.length>10||r.some(n=>!Number.isInteger(n)||n<1||n>100))throw Error('Enter a weight and valid reps for each lift.');ex[i]={weight,reps:r.join(','),unit:EX[i].unit,effort:String(data.get('effort'+i)),form:String(data.get('form'+i)),setup:String(data.get('setup'+i)||'')};}
  const km=M.n(data.get('km'));if(kind==='run'&&!(km>0&&km<=200))throw Error('Enter the actual run distance.');
  const item={id:crypto.randomUUID(),date,kind,status:'done',name:String(data.get('name')||'').trim()||({strength:'Extra strength workout',run:'Extra run',walk:'Walk',other:'Other activity'}[kind]),durationMinutes:minutes,distanceKm:['run','walk'].includes(kind)?km:null,rpe:M.n(data.get('rpe')),terrain:String(data.get('terrain')||''),exercises:ex,notes:String(data.get('notes')||''),createdAt:new Date().toISOString()};
  if(!Array.isArray(state.extraWorkouts))state.extraWorkouts=[];state.extraWorkouts.push(item);if(safeSave()){close();window.render();}
 }
 function statusMark(s){return s.code==='done'?'<span class="hub-status done" aria-label="Activity recorded">✓</span>':s.code==='unlogged'?'<span class="hub-status unlogged" aria-label="No workout logged">×</span>':s.code==='rest'?'<span class="hub-status rest" aria-label="Recovery">−</span>':'<span class="hub-status neutral">·</span>'}
 function calendar(){
  const runState=snapshot();if(window.strydeAccountStatus?.().signedIn&&!runState.attempted&&!runState.busy&&typeof window.strydeLoadStrava==='function')requestAnimationFrame(()=>{const s=snapshot();if(!s.attempted&&!s.busy)void window.strydeLoadStrava();});
  const rows=all();ROOT.querySelectorAll('.daypill').forEach((el,i)=>{const d=dateFor(state.week,i),date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),s=M.dayStatus(date,rows),node=el.querySelector('small');if(node)node.innerHTML=statusMark(s);el.title=date+' · '+s.label;});
  if(!['today','plan'].includes(view))return;
  ROOT.querySelectorAll('[data-hub-mounted]').forEach(x=>x.remove());const after=ROOT.querySelector('.hero')||ROOT.firstElementChild;
  const action=document.createElement('div');action.className='hub-today-actions';action.dataset.hubMounted='actions';action.innerHTML='<button class="btn" data-hub="extra">＋ Log extra workout</button><button class="hub-link" data-hub="calendar-mode">'+(calendarMode==='week'?'View month':'View week')+'</button>';after?.after(action);
  const b=M.due();if(b.isDue){const due=document.createElement('button');due.className='hub-due';due.dataset.hubMounted='due';due.dataset.hub='weight';due.innerHTML='<span>Body-weight check-in due</span><b>Log weight →</b>';action.after(due);}
  const benchmark=(state.benchmarkCycles||[]).find(x=>x.targetDate<=M.iso()&&!x.followupLoggedOn);if(benchmark){const due=document.createElement('button');due.className='hub-due';due.dataset.hubMounted='photo-due';due.dataset.hub='photo-due';due.innerHTML='<span>Optional photo comparison is due</span><b>View benchmark →</b>';action.after(due);}
  const strip=ROOT.querySelector('.daystrip'),nav=ROOT.querySelector('.weeknav');if(strip)strip.hidden=calendarMode==='month';if(nav)nav.hidden=calendarMode==='month';
  if(calendarMode==='month'){
   const p=M.period(calendarMonth),first=new Date(p.start+'T12:00:00Z'),offset=(first.getUTCDay()+6)%7,count=Number(p.last.slice(-2));
   const box=document.createElement('section');box.className='hub-month';box.dataset.hubMounted='calendar';box.innerHTML=`<header><button class="btn" data-hub="calendar-prev" aria-label="Previous month">‹</button><b>${first.toLocaleDateString([],{month:'long',year:'numeric',timeZone:'UTC'})}</b><button class="btn" data-hub="calendar-next" aria-label="Next month">›</button></header><div class="hub-month-grid">${['M','T','W','T','F','S','S'].map(x=>'<small>'+x+'</small>').join('')}${'<span></span>'.repeat(offset)}${Array.from({length:count},(_,i)=>{const date=p.start.slice(0,8)+String(i+1).padStart(2,'0'),s=M.dayStatus(date,rows);return `<button data-hub="day" data-date="${date}" class="${date===M.iso()?'is-today':''}" aria-label="${date}: ${esc(s.label)}"><b>${i+1}</b>${statusMark(s)}</button>`}).join('')}</div><p>✓ Activity recorded · × Past planned day with no log · − Recovery<br>Imported runs update after Strava sync.</p>`;
   strip?.parentElement.append(box);
  }
 }
 function dayDetail(date){const rows=all().filter(r=>r.date===date),p=M.planOn(date);modal(dateLabel(date),`<p>Planned: ${esc(p?.name||'No scheduled session')}</p>${rows.map(r=>`<article class="hub-record"><div><b>${esc(r.name)}</b><small>${esc(r.source)}</small></div><span>${r.distance?rnd(r.distance)+' km':r.minutes?rnd(r.minutes)+' min':'Sets recorded'}</span></article>`).join('')||'<p>No completed activity has been logged.</p>'}${date<=M.iso()?`<button class="btn orange" data-hub="extra-date" data-date="${date}">Log workout on this date</button>`:''}${p?`<button class="btn" data-hub="open-plan" data-week="${p.week}" data-day="${p.day}">Open scheduled day</button>`:''}`);}
 const originalRender=window.render;window.render=function(...args){if(view==='progress'){progress();return;}const r=originalRender.apply(this,args);calendar();return r;};
 // Let extra strength sessions guide the next prescription without rewriting planned logs.
 const oldLast=window.lastLift;window.lastLift=function(i){const latest=M.records(state,[]).filter(r=>r.kind==='strength'&&r.exercises?.[i]&&M.n(r.exercises[i].weight)>0&&M.unit(r.exercises[i].unit)===M.unit(EX[i].unit)).at(-1);return latest?{...latest.exercises[i],performed_on:latest.date}:oldLast(i);};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-hub]');if(!b)return;const a=b.dataset.hub;
  if(a==='close')close();else if(a==='extra')extra();else if(a==='extra-date')extra(b.dataset.date);else if(a==='add-exercise')addExercise();else if(a==='remove-exercise'){extraRows=extraRows.filter(i=>i!==Number(b.dataset.i));b.closest('fieldset').remove();}
  else if(a==='tab'){tab=b.dataset.tab;progress();}else if(a==='weight'){tab='body';window.go('progress');}
  else if(a==='photo-due'){tab='photos';window.go('progress');}
  else if(a==='calendar-mode'){calendarMode=calendarMode==='week'?'month':'week';window.render();}
  else if(a==='calendar-prev'||a==='calendar-next'){const d=new Date(calendarMonth+'-01T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+(a==='calendar-next'?1:-1));calendarMonth=d.toISOString().slice(0,7);window.render();}
  else if(a==='day')dayDetail(b.dataset.date);else if(a==='open-plan'){state.week=Number(b.dataset.week);state.selectedDay=Number(b.dataset.day);close();window.go('today');}
  else if(a==='snooze-weight'){state.bodyCheckSettings={...state.bodyCheckSettings,snoozeUntil:M.add(M.iso(),1)};safeSave();progress();}
  else if(a==='delete-extra'&&confirm('Remove this extra workout? Your scheduled plan will not change.')){const r=(state.extraWorkouts||[]).find(x=>x.id===b.dataset.id);if(r)r.deleted=true;safeSave();window.render();}
  else if(a==='delete-weight'&&confirm('Remove this weight check?')){state.bodyChecks=(state.bodyChecks||[]).filter(x=>x.id!==b.dataset.id);safeSave();progress();}
  else if(a==='merge-run'&&confirm('Count these as one run? Both original records will be preserved.')){state.runDuplicateLinks={...state.runDuplicateLinks,[b.dataset.id]:b.dataset.strava};safeSave();progress();}
 });
 document.addEventListener('change',e=>{if(e.target.id==='hub-month'){if(/^\d{4}-\d{2}$/.test(e.target.value)){month=e.target.value;progress();}}
  if(e.target.id==='hub-extra-kind'&&dialog){const kind=e.target.value;dialog.querySelector('[data-extra-run]').hidden=!['run','walk'].includes(kind);dialog.querySelector('[data-extra-strength]').hidden=kind!=='strength';dialog.querySelectorAll('[data-extra-strength] input,[data-extra-strength] select').forEach(x=>x.disabled=kind!=='strength');dialog.querySelector('input[name=km]').required=kind==='run';}
 });
 document.addEventListener('submit',e=>{if(e.target.id==='hub-extra-form'){e.preventDefault();try{if(e.target.reportValidity())saveExtra(e.target)}catch(err){e.target.querySelector('.hub-error').textContent=err.message}}
  else if(e.target.id==='hub-weight-form'){e.preventDefault();if(!e.target.reportValidity())return;const f=new FormData(e.target),date=String(f.get('date')),kg=M.n(f.get('kg'));if(!M.validDate(date)||date>M.iso()||!(kg>=20&&kg<=400))return;if(!Array.isArray(state.bodyChecks))state.bodyChecks=[];const old=state.bodyChecks.find(x=>x.date===date);if(old&&!confirm('Replace this date’s weight check?'))return;const row={id:old?.id||crypto.randomUUID(),date,kg,note:String(f.get('note')||'')};state.bodyChecks=state.bodyChecks.filter(x=>x.date!==date);state.bodyChecks.push(row);state.bodyCheckSettings={...state.bodyCheckSettings,snoozeUntil:null};safeSave();progress();}
  else if(e.target.id==='hub-weight-settings'){e.preventDefault();const f=new FormData(e.target);state.bodyCheckSettings={...state.bodyCheckSettings,cadenceDays:Number(f.get('cadence')),reminders:f.has('enabled')};safeSave();progress();}
 });
 window.addEventListener('stryde-runs-changed',()=>{if(view==='progress'&&['overview','strength'].includes(tab))progress();else if(['today','plan'].includes(view))calendar();});
 window.addEventListener('stryde-account-change',()=>{close();requestAnimationFrame(()=>{if(view==='progress'&&tab!=='body')progress();else if(['today','plan'].includes(view))calendar();});});
 window.strydeTrainingHub={progress,extra,calendar,all,setTab:t=>{tab=t;window.go('progress')}};
 if(view==='progress')progress();else calendar();
})();
