
window.go=function(v){view=v;render();window.scrollTo(0,0)};
window.selectDay=function(d){state.selectedDay=Math.max(0,Math.min(6,d));save();render()};
window.changeWeek=function(delta){state.week=Math.max(1,Math.min(11,state.week+delta));const d=new Date(),w=Math.floor((new Date(d.getFullYear(),d.getMonth(),d.getDate(),12)-START)/604800000)+1;state.selectedDay=state.week===w?(d.getDay()+6)%7:0;save();render()};
window.openSession=function(d){sessionDay=d;sessionTab='workout';muscleSide='both';view='session';render();window.scrollTo(0,0)};
window.setSessionTab=function(t){sessionTab=t;render()};
window.setSide=function(t){muscleSide=t;render()};
window.openExercise=function(i){selectedExercise=i;view='exercise';render();window.scrollTo(0,0)};
window.saveLift=function(){const i=selectedExercise,e=EX[i],weight=Number(document.getElementById('lift-weight').value),reps=Array.from({length:e.sets},(_,j)=>document.getElementById('rep'+j).value.trim());if(!Number.isFinite(weight)||weight<=0||reps.some(r=>!r||Number(r)<1)){alert('Enter a positive weight and repetitions for every set.');return}const l=log(sessionDay);l.exercises=l.exercises||{};l.exercises[i]={weight,reps:reps.join(','),effort:document.getElementById('lift-effort').value,form:document.getElementById('lift-form').value,unit:e.unit};if(l.status!=='done')l.status='in_progress';state.logs[key(sessionDay)]=l;save();const ids=idsFor(sessionDay),next=ids.indexOf(i)+1;if(next<ids.length){selectedExercise=ids[next];view='exercise'}else{view='session'}render();window.scrollTo(0,0)};
window.finishSession=function(){const d=sessionDay,l=log(d),ids=idsFor(d),missing=ids.filter(i=>!l.exercises?.[i]);if(missing.length&&!confirm(missing.length+' exercises have no saved sets. Finish anyway?'))return;l.status='done';state.logs[key(d)]=l;save();const eligible=ids.filter(i=>{let p=l.exercises?.[i],e=EX[i];if(!p||p.form!=='good'||p.effort==='hard')return false;let reps=String(p.reps).split(',').map(Number);return reps.length===e.sets&&reps.every(n=>n>=e.reps+2)});if(eligible.length){showUpgrade(eligible,0)}else{alert('Workout saved. STRYDE will use these sets to plan your next session.');view='today';render()}};
function showUpgrade(ids,pos){if(pos>=ids.length){view='today';render();return}let i=ids[pos],e=EX[i],l=log(sessionDay).exercises[i],w=Number(l.weight);root.innerHTML='<div class="backbar"><button onclick="showUpgradeDone()">‹</button><h3>Progression review</h3><button onclick="showUpgradeDone()">×</button></div><div class="hero"><div class="eyebrow">NEXT SESSION</div><h1>Ready for the next weight?</h1><p>You completed all sets with controlled form. The increase is optional.</p></div><div class="card"><h3>'+esc(e.name)+'</h3><div class="lift-head" style="margin:15px 0"><div class="tile"><small>CURRENT</small><strong>'+w+' '+esc(e.unit)+'</strong></div><div class="tile"><small>NEXT</small><strong>Trial only</strong></div></div><label>Next available weight ('+esc(e.unit)+')<input id="next-load" type="number" min="'+(w+.01)+'" step=".5" value="'+(w+(e.unit==='lb per hand'?1:2.5))+'"></label><button class="btn orange" style="width:100%;margin:9px 0" onclick="approveUpgrade('+i+','+w+','+pos+')">Yes, try next weight</button><button class="btn" style="width:100%" onclick="declineUpgrade('+pos+')">Keep current weight</button><p class="muted">If your form deteriorates next session, use the previous weight instead.</p></div>';window.scrollTo(0,0)}
window.approveUpgrade=function(i,previous,pos){let weight=Number(document.getElementById('next-load').value);if(!Number.isFinite(weight)||weight<=previous){alert('Enter the next available weight above your current load.');return}state.approvedLoads[i]={weight,previous,approvedAt:new Date().toISOString()};save();let l=log(sessionDay),eligible=idsFor(sessionDay).filter(j=>{let p=l.exercises?.[j],e=EX[j];return p&&p.form==='good'&&p.effort!=='hard'&&String(p.reps).split(',').map(Number).every(n=>n>=e.reps+2)});showUpgrade(eligible,pos+1)};
window.declineUpgrade=function(pos){let l=log(sessionDay),eligible=idsFor(sessionDay).filter(j=>{let p=l.exercises?.[j],e=EX[j];return p&&p.form==='good'&&p.effort!=='hard'&&String(p.reps).split(',').map(Number).every(n=>n>=e.reps+2)});showUpgrade(eligible,pos+1)};
window.showUpgradeDone=function(){view='today';render()};
window.saveRun=function(){let d=sessionDay,l=log(d);l.actual=document.getElementById('run-distance').value;l.minutes=document.getElementById('run-time').value;l.effort=document.getElementById('run-effort').value;l.status='done';state.logs[key(d)]=l;save();view='today';render()};
window.saveProfile=function(){for(let k of ['weight','height','waist'])state.profile[k]=document.getElementById(k).value;save();render()};
window.addMilestone=function(){let title=document.getElementById('goal-title').value.trim(),date=document.getElementById('goal-date').value;if(!title||!date){alert('Enter a goal and date.');return}state.milestones.forEach(m=>{if(m.status==='active')m.status='paused'});state.milestones.push({id:'goal-'+Date.now(),title,date,status:'active'});save();render()};
window.finishMilestone=function(id){let m=state.milestones.find(x=>x.id===id);if(m&&confirm('Mark this milestone complete? Past workouts will remain saved.')){m.status='completed';save();render()}};
window.exportData=function(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='stryde-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
let touchX=null;document.addEventListener('touchstart',e=>{if(e.target.closest('#daystrip'))touchX=e.changedTouches[0].screenX},{passive:true});document.addEventListener('touchend',e=>{if(touchX===null)return;let dx=e.changedTouches[0].screenX-touchX;touchX=null;if(Math.abs(dx)>40)selectDay((state.selectedDay??0)+(dx<0?1:-1))},{passive:true});
render();
